################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/ap \
App/ap/macro \
App/ap/ui \
App/common/src \
App/common/src/lcd \
App/hw \
App/hw/src \
App/hw/src/lvgl \
App/hw/src/usb/core \
App/hw/src/usb/usb_cdc \
App/hw/src/usb/usb_hid \
App/hw/src/usb/usb_msc \
App/hw/src/usb \
App/lib/lvgl/src/core \
App/lib/lvgl/src/display \
App/lib/lvgl/src/draw \
App/lib/lvgl/src/draw/nxp/pxp \
App/lib/lvgl/src/draw/nxp/vglite \
App/lib/lvgl/src/draw/renesas/dave2d \
App/lib/lvgl/src/draw/sdl \
App/lib/lvgl/src/draw/sw/blend/helium \
App/lib/lvgl/src/draw/sw/blend \
App/lib/lvgl/src/draw/sw/blend/neon \
App/lib/lvgl/src/draw/sw \
App/lib/lvgl/src/draw/vg_lite \
App/lib/lvgl/src/drivers/display/drm \
App/lib/lvgl/src/drivers/display/fb \
App/lib/lvgl/src/drivers/display/ili9341 \
App/lib/lvgl/src/drivers/display/lcd \
App/lib/lvgl/src/drivers/display/renesas_glcdc \
App/lib/lvgl/src/drivers/display/st7735 \
App/lib/lvgl/src/drivers/display/st7789 \
App/lib/lvgl/src/drivers/display/st7796 \
App/lib/lvgl/src/drivers/evdev \
App/lib/lvgl/src/drivers/glfw \
App/lib/lvgl/src/drivers/libinput \
App/lib/lvgl/src/drivers/nuttx \
App/lib/lvgl/src/drivers/qnx \
App/lib/lvgl/src/drivers/sdl \
App/lib/lvgl/src/drivers/wayland \
App/lib/lvgl/src/drivers/windows \
App/lib/lvgl/src/drivers/x11 \
App/lib/lvgl/src/font \
App/lib/lvgl/src/indev \
App/lib/lvgl/src/layouts/flex \
App/lib/lvgl/src/layouts/grid \
App/lib/lvgl/src/layouts \
App/lib/lvgl/src/libs/barcode \
App/lib/lvgl/src/libs/bin_decoder \
App/lib/lvgl/src/libs/bmp \
App/lib/lvgl/src/libs/ffmpeg \
App/lib/lvgl/src/libs/freetype \
App/lib/lvgl/src/libs/fsdrv \
App/lib/lvgl/src/libs/gif \
App/lib/lvgl/src/libs/libjpeg_turbo \
App/lib/lvgl/src/libs/libpng \
App/lib/lvgl/src/libs/lodepng \
App/lib/lvgl/src/libs/lz4 \
App/lib/lvgl/src/libs/qrcode \
App/lib/lvgl/src/libs/rle \
App/lib/lvgl/src/libs/rlottie \
App/lib/lvgl/src/libs/tiny_ttf \
App/lib/lvgl/src/libs/tjpgd \
App/lib/lvgl/src \
App/lib/lvgl/src/misc/cache \
App/lib/lvgl/src/misc \
App/lib/lvgl/src/osal \
App/lib/lvgl/src/others/file_explorer \
App/lib/lvgl/src/others/fragment \
App/lib/lvgl/src/others/gridnav \
App/lib/lvgl/src/others/ime \
App/lib/lvgl/src/others/imgfont \
App/lib/lvgl/src/others/monkey \
App/lib/lvgl/src/others/observer \
App/lib/lvgl/src/others/snapshot \
App/lib/lvgl/src/others/sysmon \
App/lib/lvgl/src/others/vg_lite_tvg \
App/lib/lvgl/src/stdlib/builtin \
App/lib/lvgl/src/stdlib/clib \
App/lib/lvgl/src/stdlib \
App/lib/lvgl/src/stdlib/micropython \
App/lib/lvgl/src/stdlib/rtthread \
App/lib/lvgl/src/themes/default \
App/lib/lvgl/src/themes \
App/lib/lvgl/src/themes/mono \
App/lib/lvgl/src/themes/simple \
App/lib/lvgl/src/tick \
App/lib/lvgl/src/widgets/animimage \
App/lib/lvgl/src/widgets/arc \
App/lib/lvgl/src/widgets/bar \
App/lib/lvgl/src/widgets/button \
App/lib/lvgl/src/widgets/buttonmatrix \
App/lib/lvgl/src/widgets/calendar \
App/lib/lvgl/src/widgets/canvas \
App/lib/lvgl/src/widgets/chart \
App/lib/lvgl/src/widgets/checkbox \
App/lib/lvgl/src/widgets/dropdown \
App/lib/lvgl/src/widgets/image \
App/lib/lvgl/src/widgets/imagebutton \
App/lib/lvgl/src/widgets/keyboard \
App/lib/lvgl/src/widgets/label \
App/lib/lvgl/src/widgets/led \
App/lib/lvgl/src/widgets/line \
App/lib/lvgl/src/widgets/list \
App/lib/lvgl/src/widgets/lottie \
App/lib/lvgl/src/widgets/menu \
App/lib/lvgl/src/widgets/msgbox \
App/lib/lvgl/src/widgets/objx_templ \
App/lib/lvgl/src/widgets/property \
App/lib/lvgl/src/widgets/roller \
App/lib/lvgl/src/widgets/scale \
App/lib/lvgl/src/widgets/slider \
App/lib/lvgl/src/widgets/span \
App/lib/lvgl/src/widgets/spinbox \
App/lib/lvgl/src/widgets/spinner \
App/lib/lvgl/src/widgets/switch \
App/lib/lvgl/src/widgets/table \
App/lib/lvgl/src/widgets/tabview \
App/lib/lvgl/src/widgets/textarea \
App/lib/lvgl/src/widgets/tileview \
App/lib/lvgl/src/widgets/win \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \

